### ISSUE TITLE
Welcome to myrestro: Next button arrow, color not the same as the theme 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#1]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Next button arrow, color not the same as the theme 

![Orderzz (9)](https://user-images.githubusercontent.com/46443551/94009827-a01d9f00-fdc2-11ea-92d8-5fd1da835978.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : done
![image](https://user-images.githubusercontent.com/69953145/94120973-63a77d00-fe6e-11ea-8239-3aad0911c5b9.png)
