### ISSUE TITLE
Home page: View basket, your basket screen is missing it will be visible when the order value is less than 100 AED

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#10]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. View basket, your basket screen is missing it will be visible when the order value is less than 100 AED

**Comment by anjaliwebvillee** [comment]
@harshasawawebvillee  this point is related to (polygon & sphere) zone data .we are working on it

**Comment by anjaliwebvillee** [comment]
done
