### ISSUE TITLE
Menu item recommendation, the text should be in proper lines because other items add button alignment issue occurs.

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#103]
Steps to reproduce

Browser: Login

1. Food review screen
2. Menu item recommendation, the text should be in proper lines because other items add button alignment issue occurs.

![Screenshot_2020-12-03-11-25-38-336704129571305702670](https://user-images.githubusercontent.com/46443551/100971580-3ad1f100-355d-11eb-9ab0-2ff9c515d85f.jpg)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
