### ISSUE TITLE
Login: Your orders, click here to cancel order display these line below the total price in reponsive 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#104]
Steps to reproduce

Browser: Chrome

1. Login
2. Your orders, click here to cancel order display these line below the total price in reponsive 

![83b4ecac-78c4-45d8-9e1c-2a62fab72da9](https://user-images.githubusercontent.com/46443551/100971719-77055180-355d-11eb-9836-a5b36f993d76.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
