### ISSUE TITLE
Login: Order placed screen, arrow button issue 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#105]
Steps to reproduce

Device: Samsung m21
Browser: Chrome

1. Login
2. Order placed screen, arrow button issue 

![Screenshot_20201203-112103_Chrome](https://user-images.githubusercontent.com/46443551/100971857-b9c72980-355d-11eb-8dca-209eb6232b4d.jpg)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
