### ISSUE TITLE
Home page: View basket, Customize This Instead of Customize this 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#11]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. View basket, Customize This Instead of Customize this 

![image](https://user-images.githubusercontent.com/46443551/94016534-d90e4180-fdcb-11ea-80a0-962e2ecada8a.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
