### ISSUE TITLE
Home page: View basket, Customize this pop-up design screen not the same as the design 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#12]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. View basket, Customize this pop-up design screen not the same as the design 

![image](https://user-images.githubusercontent.com/46443551/94016848-4cb04e80-fdcc-11ea-9b54-298eaf871dd7.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
