### ISSUE TITLE
Restaurant Box view, When we select box view from admin then the design issue occurs on the website

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#123]
Steps to reproduce

Browser: Chrome

1. Restaurant Box view, When we select box view from admin then the design issue occurs on the website

![8b68d346-1cf5-4cd0-aa64-166ddb357ddb](https://user-images.githubusercontent.com/46443551/102315800-c9516400-3f9a-11eb-858f-72775cb996be.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
