### ISSUE TITLE
The next arrow button should be center aligned

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#128]
Steps to reproduce

Device: Android/ ios
Browser: Chrome/ Safari

1. The next arrow button should be center-aligned

![IMG20201216175834](https://user-images.githubusercontent.com/46443551/102349422-501d3580-3fc9-11eb-8a64-ba114e627a5b.jpg)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
