### ISSUE TITLE
Home page: Review food, Shipping Cost (1.5km) not visible 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#13]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Review food, Shipping Cost (1.5km) not visible 

![image](https://user-images.githubusercontent.com/46443551/94018130-dca2c800-fdcd-11ea-9efd-f5804fdb1655.png)

**Comment by anjaliwebvillee** [comment]
@harshasawawebvillee this point is related to (polygon & sphere) zone data .we are working on it

**Comment by anjaliwebvillee** [comment]
done
