### ISSUE TITLE
Menu bar: Your orders, Order Data Not Found should be center-aligned

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#135]
Step to reproduce 

Browser: Chrome 

1. Menu bar
2. Your orders, Order Data Not Found should be center-aligned

![image](https://user-images.githubusercontent.com/46443551/102760509-998bcd00-439b-11eb-8a09-3322b543c1f5.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
