### ISSUE TITLE
After disabling Menu item Recommendations then recommendations not visible at application.

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#138]
Step to reproduce

Browser: Chrome

1. Admin
2. Payments, Menu item Recommendations
3. After disable Menu item Recommendations
4. Application side, Menu item Recommendations is still visible 

Excepted result: After disabling Menu item Recommendations then recommendations not visible at application.

Actual result: Menu item Recommendations still visible after disabling from the admin

**Comment by anjaliwebvillee** [comment]
Done
