### ISSUE TITLE
Home page: Review food, back button & review food text alignment issue, not the same as PDF

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#14]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Review food, back button & review food text alignment issue, not the same as PDF

![Fodso-Consumer-Nitin1073307974940763750-pdf](https://user-images.githubusercontent.com/46443551/94019090-fee91580-fdce-11ea-933c-b85d8a3efd48.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
