### ISSUE TITLE
Menu: When we click on Menu sub categories then the menu should be highlighted in blue color 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#140]
Step to reproduce

Browser: Chrome

1. Admin
2. Click on Menu
3. The menu highlighted in blue color
4. Select Categories or Items
5. The menu highlighted color disappear 

Expected Result: When we click on Menu sub categories then the menu should be highlighted in blue color 

Actual result: Menu was not highlighted in blue color 

![35ef9db2-35eb-46df-9b9c-558961dc7bdb](https://user-images.githubusercontent.com/46443551/102854923-9818de00-4449-11eb-97b0-7ee0387bbcf5.png)

![48a56941-8630-45f8-9c30-15c6af6efdbc](https://user-images.githubusercontent.com/46443551/102854951-a8c95400-4449-11eb-89e2-68b868c0121a.png)

**Comment by anjaliwebvillee** [comment]
close
