### ISSUE TITLE
Categories: The product name should be scroll if it's a long name 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#144]
Steps to reproduce

Device: Android Phone
OS: Android 10
Browser: Chrome

1. Open Application
2. Box view design 
3. Categories, product name visible in 2 line
4. The product name should be scroll if it's a long name 

Excepted result: The product name should be visible in one line

Actual result: product name visible in 2 lines 

![40b7166a-04ee-4f59-827d-d86c542035ae](https://user-images.githubusercontent.com/46443551/102877552-f3a89300-446c-11eb-8248-4b363d4992ca.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
