### ISSUE TITLE
View Basket: Customize this, Edit customize text visible in 2 lines it should be visible in 1 line

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#145]
Steps to reproduce

Device: Android Phone
OS: Android 10
Browser: Chrome

1. Open Application
2. Add items
3. View basket
4. Customize this, Edit customize text visible in 2 lines it should be visible in 1 line

Expected result: After customized items, edit customized line should be visible in 2 lines 

Actual result: currently edit customized text will be visible in 2 lines 

![940f67b0-7bbb-4ed8-98e4-abfac2faa014](https://user-images.githubusercontent.com/46443551/102878760-be04a980-446e-11eb-9e15-1e1bb349de5b.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
