### ISSUE TITLE
If we change the delivery location from the checkout and select the online payment option then customer redirect to the payment gateway page and proceed for payment

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#146]
Steps to reproduce

Browser: Chrome

1. Open Application
2. Select the pickup location
3. Add items
4. Select location
5. checkout page, change location 
6. Select a different location 
7. Checkout page, Apply promo code
8. Select the online payment, then nothing happens 

Expected result: If we change the delivery location from the checkout and select the online payment option then customer redirect to the payment gateway page and proceed for payment

Actual result:  After changing the delivery location than online payment not working

**Comment by harshasawawebvillee** [comment]
@anjaliwebvillee without changing the location, online payment not working for the first time only.

https://www.loom.com/share/10d648eaabab4a91ac7ab3e2c7000953

**Comment by anjaliwebvillee** [comment]
Done
