### ISSUE TITLE
Home page: Place order, In phone number, field phone icon is missing   

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#15]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Place order, In phone number, field phone icon is missing   

![image](https://user-images.githubusercontent.com/46443551/94021252-70c25e80-fdd1-11ea-82b5-28e1f8e1421c.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
![image](https://user-images.githubusercontent.com/69953145/94120673-07dcf400-fe6e-11ea-9a9f-84274f3da3dd.png)
