### ISSUE TITLE
Place order, When we click on the Send OTP then design issue occurs 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#16]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Place order, When we click on the Send OTP then design issue occurs 

![image (22)](https://user-images.githubusercontent.com/46443551/94021879-22618f80-fdd2-11ea-97a5-245d2880fa05.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
