### ISSUE TITLE
Home page: Phone verification should be in 2 lines as the same as design.

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#17]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Phone verification should be in 2 lines as the same as design.

![image](https://user-images.githubusercontent.com/46443551/94103460-65fbde00-fe52-11ea-94a7-a34fc67b3e07.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
![image](https://user-images.githubusercontent.com/69953145/94120537-dcf2a000-fe6d-11ea-8b48-fc5a99c88819.png)

**Comment by harshasawawebvillee** [comment]
@sapnawebvillee Screen not updated
