### ISSUE TITLE
Home page: Enter OTP screen, OTP Not Received instead of OTP not received 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#18]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Enter OTP screen, OTP Not Received instead of OTP not received 

![image](https://user-images.githubusercontent.com/46443551/94103744-f803e680-fe52-11ea-83c3-dc17b7d0cb91.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
