### ISSUE TITLE
Home page: Personal Details, Email id validation message should be visible if email id is wrong 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#19]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Personal Details, Email id validation message should be visible if email id is wrong 

![image (23)](https://user-images.githubusercontent.com/46443551/94104316-5b424880-fe54-11ea-8495-55dd88eee169.png)

**Comment by anjaliwebvillee** [comment]
done
