### ISSUE TITLE
Next: Enable location, above location image color not the same as design 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#2]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Next
3. Enable location, above location image color not the same as design 

![Orderzz (10)](https://user-images.githubusercontent.com/46443551/94010342-731dbc00-fdc3-11ea-9055-07dacd8d1031.png)

**Comment by danishwebvillee** [comment]
Image color coming from admin selected theme color
