### ISSUE TITLE
Confirm Address, Flat no instead of Flat No

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#20]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Confirm Address, Flat no instead of Flat No
 

![image](https://user-images.githubusercontent.com/46443551/94110112-ba598a80-fe5f-11ea-830f-e72461e2ba72.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
