### ISSUE TITLE
Checkout: Deliver to, space required after deliver to 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#22]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Checkout
3. Deliver to, space required after deliver to 

![Fodso-Consumer-Nitin1073307974940763750-pdf (1)](https://user-images.githubusercontent.com/46443551/94111246-68b1ff80-fe61-11ea-84f6-7d662c594b9e.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
