### ISSUE TITLE
Checkout: Add a new card, unable to add a new card

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#23]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Checkout
3. Add a new card, unable to add a new card

![image](https://user-images.githubusercontent.com/46443551/94111995-6c925180-fe62-11ea-9dec-6989c0cca272.png)

**Comment by anjaliwebvillee** [comment]
@harshasawawebvillee depends on payment integration
