### ISSUE TITLE
Checkout: Choose payment, saving instead of Savings

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#25]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Checkout
3. Choose payment, saving instead of Savings

![Fodso-Consumer-Nitin1073307974940763750-pdf (2)](https://user-images.githubusercontent.com/46443551/94113215-2b02a600-fe64-11ea-8227-b2a7bb885e02.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
