### ISSUE TITLE
Checkout: Choose payment, Shipping cost is missing 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#26]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Checkout
3. Choose payment, Shipping cost is missing 

![Fodso-Consumer-Nitin1073307974940763750-pdf (3)](https://user-images.githubusercontent.com/46443551/94113402-77e67c80-fe64-11ea-98cc-cb4495014773.png)

**Comment by vaishaliwebvillee** [comment]
shipping cost is hidden for now

**Comment by anjaliwebvillee** [comment]
@harshasawawebvillee  this point is related to (polygon & sphere) zone data .we are working on it
