### ISSUE TITLE
Order placed screen color & design issue 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#27]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Order placed screen color & design issue 

![Orderzz (13)](https://user-images.githubusercontent.com/46443551/94118752-9308ba80-fe6b-11ea-8c3f-8aad0665f04f.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
