### ISSUE TITLE
Welcome Page: The hotel logo did not fit properly according to the design 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#31]
Step to reproduce

Browser: Chrome

1. Go to https://menu.orderrzz.com/Hotel-J
2. Welcome Page
3. The hotel logo did not fit properly according to the design 

![image](https://user-images.githubusercontent.com/46443551/94136382-7cba2900-fe82-11ea-99e4-c2e8d9ef27de.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
