### ISSUE TITLE
Enable location, When we click on No, Do it later then button and text color not according to theme 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#4]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Enable location, When we click on No, Do it later then button and text color not according to theme 

![image](https://user-images.githubusercontent.com/46443551/94011425-f68bdd00-fdc4-11ea-8e98-d36bf1455841.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
