### ISSUE TITLE
Restaurants: First, When the website loads the first time it always shows orange color? It will be loads according to the website hex color. 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#49]
Step to reproduce

Browser: Chrome

1. Restaurants
2. First, When the website loads the first time it always shows orange color? It will be loads according to the website hex color.

**Comment by amitwebvillee** [comment]
bydefault we set orange colour so that it occure. colour functionality occure dynamically it take some time for server responce.
