### ISSUE TITLE
Home page: Below restaurant name address not visible 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#5]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Below restaurant name address not visible 

![image](https://user-images.githubusercontent.com/46443551/94012041-ddcff700-fdc5-11ea-9dfc-5b00c2fca9df.png)

![image](https://user-images.githubusercontent.com/46443551/94012075-e7f1f580-fdc5-11ea-928c-a08a838c64a8.png)

**Comment by vaishaliwebvillee** [comment]
this will show from restoraunt side
