### ISSUE TITLE
Home page: Before categories, the address should be in 2 lines or it should be visible like for example (Aru plaza, MG Road....)

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#6]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Before categories, the address should be in 2 lines or it should be visible like for example (Aru plaza, MG Road....)

![image](https://user-images.githubusercontent.com/46443551/94012980-14f2d800-fdc7-11ea-9c63-10e57ef91bf1.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
