### ISSUE TITLE
Restaurants: Order laced screen, circle inner icon should be according to restaurant color. 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#72]
Step to reproduce

Browser: Chrome

1. Restaurants
2. Order laced screen, circle inner icon should be according to restaurant color. 

![85974a10-33b5-4abd-9905-2572b044a9fe](https://user-images.githubusercontent.com/46443551/100328445-897a0b00-2ff2-11eb-8814-ce298ca6acb6.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
