### ISSUE TITLE
Restaurants: Order placed screen, arrow and content should be semi bold, when order completes delivered text should be bold.

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#73]
Step to reproduce

Browser: Chrome

1. Restaurants
2. Order placed screen, arrow and content should be semi bold, when order completes delivered text should be bold.

![image](https://user-images.githubusercontent.com/46443551/100329386-9814f200-2ff3-11eb-9712-b28a9d5b95f5.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
