### ISSUE TITLE
Home page: Below categories, items label not the same as the design 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#8]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Below categories, items label not the same as the design 

![Orderzz (11)](https://user-images.githubusercontent.com/46443551/94013852-533cc700-fdc8-11ea-9e24-7d57f1ecd4b9.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
