### ISSUE TITLE
Review Food: Menu item recommendations, content should be visible according to capital and small letters 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#85]
Step to reproduce

Browser: Chrome

1. Restaurants
2. Review Food
3. Menu item recommendations, content should be visible according to capital and small letters 

![image](https://user-images.githubusercontent.com/46443551/100498784-b95c1680-318a-11eb-85fc-9dd8b304add2.png)

![image](https://user-images.githubusercontent.com/46443551/100498798-c0832480-318a-11eb-84d6-14ccb9e5c70d.png)

**Comment by amitwebvillee** [comment]
please provide formet of letter. presently we set first letter capital
