### ISSUE TITLE
Review Food: Menu item recommendation, When we add a recommendation  item then frame border issue and also before item image space issue

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#88]
Step to reproduce

Browser: Chrome

1. Restaurants
2. Review Food
3. Menu item recommendation, When we add a recommendation  item then frame border issue and also before item image space issue

![506211f6-5010-4f9a-9c0b-70eb15e971d2](https://user-images.githubusercontent.com/46443551/100515714-1d3f0900-31a4-11eb-958e-159fe7713788.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
