### ISSUE TITLE
Restaurants: Review Food, responsive issue, and total price font size issue

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#89]
Step to reproduce

Browser: Chrome

1. Restaurants
2. Review Food, responsive issue, and total price font size issue

![fe9728aa-5d74-4888-8eaa-2f260d2d7e79](https://user-images.githubusercontent.com/46443551/100516013-ba9b3c80-31a6-11eb-994b-8dccd8b181ea.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
