### ISSUE TITLE
Home page: Add items, view basket should not be fixed in the footer 

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#9]
Steps to reproduce

Browser: Login

1. Welcome to myrestro
2. Home page
3. Add items, view basket should not be fixed in the footer 

![image](https://user-images.githubusercontent.com/46443551/94014687-816ed680-fdc9-11ea-87db-8fd60d7d0c96.png)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Done
