### ISSUE TITLE
Home screen: Time and minimum order line break required

### ISSUE THREAD

**Issue by harshasawawebvillee** [Webvillee/orderzz_app#99]
Step to reproduce

Device: iPad

1. Home screen
2. Time and minimum order line break required

![Screenshot_2020-12-02-16-38-47-153687426906190150323](https://user-images.githubusercontent.com/46443551/100865482-67363080-34bd-11eb-8f74-3c6ea1888f19.jpg)

**Comment by sapnawebvillee** [comment]
@harshasawawebvillee : Fixed
